name: Bug Report
description: Reporte eine Bug
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Bitte joine unserem Discord Server für weitere Frage.
  - type: checkboxes
    attributes:
      label: Allgemeine Fehlersuche
      description: Sie bestätigen, dass Sie zuvor die folgenden Kontrollen durchgeführt haben.
      options:
      - label: Ich habe im Issue-tracker nach ähnlichen Problemen gesucht.
        required: true
      - label: Ich konnte den Bug auf der letzen Version des Servers Repoduzieren
        required: true
      - label: Ich habe diesen Bug auf bevorstehende Fehlerbehebungen überprüft.
        required: true
  - type: input
    id: contact
    attributes:
      label: Kontaktangaben
      description: Bitte gib dein Discord Tag an damit wir dich bei weiteren Fragen Kontaktieren können.
      placeholder: ex. .𝓐´𝓙𝓸𝓷®#2012
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Was ist passiert?
      description: Bitte beschreiben den Bug so gut es geht.
      placeholder: Erzähle uns was passiert ist!
      value: "Ich hab einen Bug gefunden!"
    validations:
      required: true
  - type: textarea
    id: what-should-happened
    attributes:
      label: Was sollte eigentlich passieren?
      description: Bitte beschreibe was du eigentlich erwartest hast.
      placeholder: Erzähle uns was passiert ist!
      value: "Ich wollte nur Essen kaufen!"
    validations:
      required: true
  - type: textarea
    id: console
    attributes:
      label: Screenshot der Console [F8]
      description: Bitte mache einen Screennshot deiner Console nach dem Bug. [F8]
      placeholder: Ziehe deinen Screenshot einfach per Drag and Drop in diese Feld oder Copy-Past einfach den Link.
    validations:
      required: true
